//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSPC.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка NAPS2. Выполняется после настройки МФУ.
        /// </summary>
        internal static string naps2 {
            get {
                return ResourceManager.GetString("naps2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Du9ueQu2
        ///Открываем &quot;Инструменты -&gt; Адресная книга&quot;
        ///Далее &quot;Файл -&gt; создать -&gt; каталог LDAP&quot;
        ///Заполняем по образцу
        ///1) Zimbra
        ///2) mail.dengisrazy.ru
        ///3) dc=ru
        ///4) 389
        ///5) uid=addressbook,ou=people,dc=dengisrazy,dc=ru
        ///
        ///затем открываем вкладку &quot;Автономно&quot; и нажимаем &quot;Загрузить сейчас&quot;
        ///Вводим необходимый пароль (уточняйте) и отмечаем пункт &quot;сохранить пароль&quot;
        ///
        ///Открываем &quot;Адресная книга&quot;=&gt;&quot;Инструменты&quot;=&gt;&quot;Настройки&quot;=&gt;&quot;Адресация&quot;. Отмечаем &quot;Сервере каталогов&quot; и выбираем сервер &quot;Zimbra&quot;
        ///
        ///Выполнить тестовую о [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Du9ueQu2
        ///Открываем &quot;Инструменты -&gt; Адресная книга&quot;
        ///Далее &quot;Файл -&gt; создать -&gt; каталог LDAP&quot;
        ///Заполняем по образцу
        ///1) Zimbra
        ///2) mail.dengisrazy.ru
        ///3) dc=ru
        ///4) 389
        ///5) uid=addressbook,ou=people,dc=dengisrazy,dc=ru
        ///
        ///затем открываем вкладку &quot;Автономно&quot; и нажимаем &quot;Загрузить сейчас&quot;
        ///Вводим необходимый пароль (уточняйте) и отмечаем пункт &quot;сохранить пароль&quot;
        ///
        ///Открываем &quot;Адресная книга&quot;=&gt;&quot;Инструменты&quot;=&gt;&quot;Настройки&quot;=&gt;&quot;Адресация&quot;. Отмечаем &quot;Сервере каталогов&quot; и выбираем сервер &quot;Zimbra&quot;.
        /// </summary>
        internal static string post_addr {
            get {
                return ResourceManager.GetString("post_addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настроить входящий и исходящий сервера, перезагрузить Thunderbird, ввести пароли для сервера получения и отправки..
        /// </summary>
        internal static string post_servers {
            get {
                return ResourceManager.GetString("post_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить подпись: Настройки=&gt;Настройки пользователя=&gt;Подпись. Подпись можно взять из отправленного ранее письма..
        /// </summary>
        internal static string post_signature {
            get {
                return ResourceManager.GetString("post_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить тестовое письмо на ЦВЗ. Должно работать автозаполнение адресата, присутствовать подпись, письмо должно отправляться и доставляться адресату..
        /// </summary>
        internal static string post_test_message {
            get {
                return ResourceManager.GetString("post_test_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняет копирование структуры каталогов, ярлыки на общий рабочий стол, правит скрипт iSpy. Добавляет скрипт Copy_Files.bat на рабочий стол пользователя DSAdmin.
        /// </summary>
        internal static string presettings {
            get {
                return ResourceManager.GetString("presettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть IP адрес принтера в браузере.
        /// </summary>
        internal static string printerSettings {
            get {
                return ResourceManager.GetString("printerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После ОС системный видеодрайвер работает не всегда корректно. При работе с некоторыми чипсетами Intel возникает проблема с разрешением изображения. Решение — установка соответствующих драйверов.
        ///
        ///
        ///14.1. Чипсет Intel H61: \\nas.dengisrazy.ru\IT\_win10\software\intel_h61_video_driver_win64.zip
        ///
        ///14.2. Чипсет Intel G41: \\nas.dengisrazy.ru\IT\_win10\software\intel_g41_video_driver_win64.exe.
        /// </summary>
        internal static string stringMarkdown {
            get {
                return ResourceManager.GetString("stringMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После установки ОС системный видеодрайвер работает не всегда корректно. При работе с некоторыми чипсетами Intel возникает проблема с разрешением изображения. Решение — установка соответствующих драйверов.
        ///                        
        ///                        
        ///14.1. Чипсет Intel H61: \\nas.dengisrazy.ru\IT\_win10\software\intel_h61_video_driver_win64.zip
        ///14.2. Чипсет Intel G41: \\nas.dengisrazy.ru\IT\_win10\software\intel_g41_video_driver_win64.exe.
        /// </summary>
        internal static string videodriver {
            get {
                return ResourceManager.GetString("videodriver", resourceCulture);
            }
        }
    }
}
